// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: input/test.proto

package protobuf;

public final class Test {
  private Test() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface OuterOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .protobuf.Inner inners = 4;
    /**
     * <code>repeated .protobuf.Inner inners = 4;</code>
     */
    java.util.List<protobuf.Test.Inner> 
        getInnersList();
    /**
     * <code>repeated .protobuf.Inner inners = 4;</code>
     */
    protobuf.Test.Inner getInners(int index);
    /**
     * <code>repeated .protobuf.Inner inners = 4;</code>
     */
    int getInnersCount();
    /**
     * <code>repeated .protobuf.Inner inners = 4;</code>
     */
    java.util.List<? extends protobuf.Test.InnerOrBuilder> 
        getInnersOrBuilderList();
    /**
     * <code>repeated .protobuf.Inner inners = 4;</code>
     */
    protobuf.Test.InnerOrBuilder getInnersOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protobuf.Outer}
   */
  public static final class Outer extends
      com.google.protobuf.GeneratedMessage
      implements OuterOrBuilder {
    // Use Outer.newBuilder() to construct.
    private Outer(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Outer(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Outer defaultInstance;
    public static Outer getDefaultInstance() {
      return defaultInstance;
    }

    public Outer getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Outer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                inners_ = new java.util.ArrayList<protobuf.Test.Inner>();
                mutable_bitField0_ |= 0x00000001;
              }
              inners_.add(input.readMessage(protobuf.Test.Inner.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          inners_ = java.util.Collections.unmodifiableList(inners_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.Test.internal_static_protobuf_Outer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.Test.internal_static_protobuf_Outer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.Test.Outer.class, protobuf.Test.Outer.Builder.class);
    }

    public static com.google.protobuf.Parser<Outer> PARSER =
        new com.google.protobuf.AbstractParser<Outer>() {
      public Outer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Outer(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Outer> getParserForType() {
      return PARSER;
    }

    // repeated .protobuf.Inner inners = 4;
    public static final int INNERS_FIELD_NUMBER = 4;
    private java.util.List<protobuf.Test.Inner> inners_;
    /**
     * <code>repeated .protobuf.Inner inners = 4;</code>
     */
    public java.util.List<protobuf.Test.Inner> getInnersList() {
      return inners_;
    }
    /**
     * <code>repeated .protobuf.Inner inners = 4;</code>
     */
    public java.util.List<? extends protobuf.Test.InnerOrBuilder> 
        getInnersOrBuilderList() {
      return inners_;
    }
    /**
     * <code>repeated .protobuf.Inner inners = 4;</code>
     */
    public int getInnersCount() {
      return inners_.size();
    }
    /**
     * <code>repeated .protobuf.Inner inners = 4;</code>
     */
    public protobuf.Test.Inner getInners(int index) {
      return inners_.get(index);
    }
    /**
     * <code>repeated .protobuf.Inner inners = 4;</code>
     */
    public protobuf.Test.InnerOrBuilder getInnersOrBuilder(
        int index) {
      return inners_.get(index);
    }

    private void initFields() {
      inners_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getInnersCount(); i++) {
        if (!getInners(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < inners_.size(); i++) {
        output.writeMessage(4, inners_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < inners_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, inners_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.Test.Outer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.Test.Outer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.Test.Outer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.Test.Outer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.Test.Outer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.Test.Outer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.Test.Outer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.Test.Outer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.Test.Outer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.Test.Outer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.Test.Outer prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Outer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.Test.OuterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.Test.internal_static_protobuf_Outer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.Test.internal_static_protobuf_Outer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.Test.Outer.class, protobuf.Test.Outer.Builder.class);
      }

      // Construct using protobuf.Test.Outer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getInnersFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (innersBuilder_ == null) {
          inners_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          innersBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.Test.internal_static_protobuf_Outer_descriptor;
      }

      public protobuf.Test.Outer getDefaultInstanceForType() {
        return protobuf.Test.Outer.getDefaultInstance();
      }

      public protobuf.Test.Outer build() {
        protobuf.Test.Outer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.Test.Outer buildPartial() {
        protobuf.Test.Outer result = new protobuf.Test.Outer(this);
        @SuppressWarnings("unused")
        int from_bitField0_ = bitField0_;
        if (innersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            inners_ = java.util.Collections.unmodifiableList(inners_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.inners_ = inners_;
        } else {
          result.inners_ = innersBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.Test.Outer) {
          return mergeFrom((protobuf.Test.Outer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.Test.Outer other) {
        if (other == protobuf.Test.Outer.getDefaultInstance()) return this;
        if (innersBuilder_ == null) {
          if (!other.inners_.isEmpty()) {
            if (inners_.isEmpty()) {
              inners_ = other.inners_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureInnersIsMutable();
              inners_.addAll(other.inners_);
            }
            onChanged();
          }
        } else {
          if (!other.inners_.isEmpty()) {
            if (innersBuilder_.isEmpty()) {
              innersBuilder_.dispose();
              innersBuilder_ = null;
              inners_ = other.inners_;
              bitField0_ = (bitField0_ & ~0x00000001);
              innersBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getInnersFieldBuilder() : null;
            } else {
              innersBuilder_.addAllMessages(other.inners_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getInnersCount(); i++) {
          if (!getInners(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.Test.Outer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.Test.Outer) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .protobuf.Inner inners = 4;
      private java.util.List<protobuf.Test.Inner> inners_ =
        java.util.Collections.emptyList();
      private void ensureInnersIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          inners_ = new java.util.ArrayList<protobuf.Test.Inner>(inners_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          protobuf.Test.Inner, protobuf.Test.Inner.Builder, protobuf.Test.InnerOrBuilder> innersBuilder_;

      /**
       * <code>repeated .protobuf.Inner inners = 4;</code>
       */
      public java.util.List<protobuf.Test.Inner> getInnersList() {
        if (innersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(inners_);
        } else {
          return innersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protobuf.Inner inners = 4;</code>
       */
      public int getInnersCount() {
        if (innersBuilder_ == null) {
          return inners_.size();
        } else {
          return innersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protobuf.Inner inners = 4;</code>
       */
      public protobuf.Test.Inner getInners(int index) {
        if (innersBuilder_ == null) {
          return inners_.get(index);
        } else {
          return innersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protobuf.Inner inners = 4;</code>
       */
      public Builder setInners(
          int index, protobuf.Test.Inner value) {
        if (innersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInnersIsMutable();
          inners_.set(index, value);
          onChanged();
        } else {
          innersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Inner inners = 4;</code>
       */
      public Builder setInners(
          int index, protobuf.Test.Inner.Builder builderForValue) {
        if (innersBuilder_ == null) {
          ensureInnersIsMutable();
          inners_.set(index, builderForValue.build());
          onChanged();
        } else {
          innersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Inner inners = 4;</code>
       */
      public Builder addInners(protobuf.Test.Inner value) {
        if (innersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInnersIsMutable();
          inners_.add(value);
          onChanged();
        } else {
          innersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Inner inners = 4;</code>
       */
      public Builder addInners(
          int index, protobuf.Test.Inner value) {
        if (innersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInnersIsMutable();
          inners_.add(index, value);
          onChanged();
        } else {
          innersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Inner inners = 4;</code>
       */
      public Builder addInners(
          protobuf.Test.Inner.Builder builderForValue) {
        if (innersBuilder_ == null) {
          ensureInnersIsMutable();
          inners_.add(builderForValue.build());
          onChanged();
        } else {
          innersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Inner inners = 4;</code>
       */
      public Builder addInners(
          int index, protobuf.Test.Inner.Builder builderForValue) {
        if (innersBuilder_ == null) {
          ensureInnersIsMutable();
          inners_.add(index, builderForValue.build());
          onChanged();
        } else {
          innersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Inner inners = 4;</code>
       */
      public Builder addAllInners(
          java.lang.Iterable<? extends protobuf.Test.Inner> values) {
        if (innersBuilder_ == null) {
          ensureInnersIsMutable();
          super.addAll(values, inners_);
          onChanged();
        } else {
          innersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Inner inners = 4;</code>
       */
      public Builder clearInners() {
        if (innersBuilder_ == null) {
          inners_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          innersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Inner inners = 4;</code>
       */
      public Builder removeInners(int index) {
        if (innersBuilder_ == null) {
          ensureInnersIsMutable();
          inners_.remove(index);
          onChanged();
        } else {
          innersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Inner inners = 4;</code>
       */
      public protobuf.Test.Inner.Builder getInnersBuilder(
          int index) {
        return getInnersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protobuf.Inner inners = 4;</code>
       */
      public protobuf.Test.InnerOrBuilder getInnersOrBuilder(
          int index) {
        if (innersBuilder_ == null) {
          return inners_.get(index);  } else {
          return innersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protobuf.Inner inners = 4;</code>
       */
      public java.util.List<? extends protobuf.Test.InnerOrBuilder> 
           getInnersOrBuilderList() {
        if (innersBuilder_ != null) {
          return innersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(inners_);
        }
      }
      /**
       * <code>repeated .protobuf.Inner inners = 4;</code>
       */
      public protobuf.Test.Inner.Builder addInnersBuilder() {
        return getInnersFieldBuilder().addBuilder(
            protobuf.Test.Inner.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.Inner inners = 4;</code>
       */
      public protobuf.Test.Inner.Builder addInnersBuilder(
          int index) {
        return getInnersFieldBuilder().addBuilder(
            index, protobuf.Test.Inner.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.Inner inners = 4;</code>
       */
      public java.util.List<protobuf.Test.Inner.Builder> 
           getInnersBuilderList() {
        return getInnersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          protobuf.Test.Inner, protobuf.Test.Inner.Builder, protobuf.Test.InnerOrBuilder> 
          getInnersFieldBuilder() {
        if (innersBuilder_ == null) {
          innersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              protobuf.Test.Inner, protobuf.Test.Inner.Builder, protobuf.Test.InnerOrBuilder>(
                  inners_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          inners_ = null;
        }
        return innersBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.Outer)
    }

    static {
      defaultInstance = new Outer(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.Outer)
  }

  public interface InnerOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string str = 1;
    /**
     * <code>required string str = 1;</code>
     */
    boolean hasStr();
    /**
     * <code>required string str = 1;</code>
     */
    java.lang.String getStr();
    /**
     * <code>required string str = 1;</code>
     */
    com.google.protobuf.ByteString
        getStrBytes();
  }
  /**
   * Protobuf type {@code protobuf.Inner}
   */
  public static final class Inner extends
      com.google.protobuf.GeneratedMessage
      implements InnerOrBuilder {
    // Use Inner.newBuilder() to construct.
    private Inner(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Inner(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Inner defaultInstance;
    public static Inner getDefaultInstance() {
      return defaultInstance;
    }

    public Inner getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Inner(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              str_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.Test.internal_static_protobuf_Inner_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.Test.internal_static_protobuf_Inner_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.Test.Inner.class, protobuf.Test.Inner.Builder.class);
    }

    public static com.google.protobuf.Parser<Inner> PARSER =
        new com.google.protobuf.AbstractParser<Inner>() {
      public Inner parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Inner(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Inner> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string str = 1;
    public static final int STR_FIELD_NUMBER = 1;
    private java.lang.Object str_;
    /**
     * <code>required string str = 1;</code>
     */
    public boolean hasStr() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string str = 1;</code>
     */
    public java.lang.String getStr() {
      java.lang.Object ref = str_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          str_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string str = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStrBytes() {
      java.lang.Object ref = str_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        str_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      str_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasStr()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getStrBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getStrBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.Test.Inner parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.Test.Inner parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.Test.Inner parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.Test.Inner parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.Test.Inner parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.Test.Inner parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.Test.Inner parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.Test.Inner parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.Test.Inner parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.Test.Inner parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.Test.Inner prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Inner}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.Test.InnerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.Test.internal_static_protobuf_Inner_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.Test.internal_static_protobuf_Inner_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.Test.Inner.class, protobuf.Test.Inner.Builder.class);
      }

      // Construct using protobuf.Test.Inner.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        str_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.Test.internal_static_protobuf_Inner_descriptor;
      }

      public protobuf.Test.Inner getDefaultInstanceForType() {
        return protobuf.Test.Inner.getDefaultInstance();
      }

      public protobuf.Test.Inner build() {
        protobuf.Test.Inner result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.Test.Inner buildPartial() {
        protobuf.Test.Inner result = new protobuf.Test.Inner(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.str_ = str_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.Test.Inner) {
          return mergeFrom((protobuf.Test.Inner)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.Test.Inner other) {
        if (other == protobuf.Test.Inner.getDefaultInstance()) return this;
        if (other.hasStr()) {
          bitField0_ |= 0x00000001;
          str_ = other.str_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStr()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.Test.Inner parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.Test.Inner) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string str = 1;
      private java.lang.Object str_ = "";
      /**
       * <code>required string str = 1;</code>
       */
      public boolean hasStr() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string str = 1;</code>
       */
      public java.lang.String getStr() {
        java.lang.Object ref = str_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          str_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string str = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStrBytes() {
        java.lang.Object ref = str_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          str_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string str = 1;</code>
       */
      public Builder setStr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        str_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string str = 1;</code>
       */
      public Builder clearStr() {
        bitField0_ = (bitField0_ & ~0x00000001);
        str_ = getDefaultInstance().getStr();
        onChanged();
        return this;
      }
      /**
       * <code>required string str = 1;</code>
       */
      public Builder setStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        str_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.Inner)
    }

    static {
      defaultInstance = new Inner(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.Inner)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Outer_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_Outer_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Inner_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_Inner_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020input/test.proto\022\010protobuf\"(\n\005Outer\022\037\n" +
      "\006inners\030\004 \003(\0132\017.protobuf.Inner\"\024\n\005Inner\022" +
      "\013\n\003str\030\001 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protobuf_Outer_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protobuf_Outer_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_Outer_descriptor,
              new java.lang.String[] { "Inners", });
          internal_static_protobuf_Inner_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protobuf_Inner_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_Inner_descriptor,
              new java.lang.String[] { "Str", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
