language: java
before_install:
 - sudo apt-get -qq update
 - ./config/setup_instructions/linux/installProtobuf.sh
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
 - ./config/setup_instructions/linux/installChrome.sh 
