# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: input/action.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='input/action.proto',
  package='protobuf.srl.action',
  serialized_pb='\n\x12input/action.proto\x12\x13protobuf.srl.action\"8\n\x06Update\x12.\n\x08\x63ommands\x18\x01 \x03(\x0b\x32\x1c.protobuf.srl.action.Command\"\x8d\x01\n\x07\x43ommand\x12\x35\n\x0b\x63ommandType\x18\x01 \x02(\x0e\x32 .protobuf.srl.action.CommandType\x12\x15\n\risUserCreated\x18\x02 \x02(\x08\x12\x13\n\x0b\x63ommandData\x18\x03 \x02(\x0c\x12\x0c\n\x04time\x18\x04 \x01(\x03\x12\x11\n\tcommandId\x18\x05 \x01(\t*[\n\x0b\x43ommandType\x12\x0e\n\nADD_STROKE\x10\x00\x12\r\n\tADD_SHAPE\x10\x01\x12\x13\n\x0fREPACKAGE_SHAPE\x10\x02\x12\x18\n\x14\x46ORCE_INTERPRETATION\x10\x03')

_COMMANDTYPE = _descriptor.EnumDescriptor(
  name='CommandType',
  full_name='protobuf.srl.action.CommandType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ADD_STROKE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADD_SHAPE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REPACKAGE_SHAPE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FORCE_INTERPRETATION', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=245,
  serialized_end=336,
)

CommandType = enum_type_wrapper.EnumTypeWrapper(_COMMANDTYPE)
ADD_STROKE = 0
ADD_SHAPE = 1
REPACKAGE_SHAPE = 2
FORCE_INTERPRETATION = 3



_UPDATE = _descriptor.Descriptor(
  name='Update',
  full_name='protobuf.srl.action.Update',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='commands', full_name='protobuf.srl.action.Update.commands', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=43,
  serialized_end=99,
)


_COMMAND = _descriptor.Descriptor(
  name='Command',
  full_name='protobuf.srl.action.Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='commandType', full_name='protobuf.srl.action.Command.commandType', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isUserCreated', full_name='protobuf.srl.action.Command.isUserCreated', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='commandData', full_name='protobuf.srl.action.Command.commandData', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='protobuf.srl.action.Command.time', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='commandId', full_name='protobuf.srl.action.Command.commandId', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=102,
  serialized_end=243,
)

_UPDATE.fields_by_name['commands'].message_type = _COMMAND
_COMMAND.fields_by_name['commandType'].enum_type = _COMMANDTYPE
DESCRIPTOR.message_types_by_name['Update'] = _UPDATE
DESCRIPTOR.message_types_by_name['Command'] = _COMMAND

class Update(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UPDATE

  # @@protoc_insertion_point(class_scope:protobuf.srl.action.Update)

class Command(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COMMAND

  # @@protoc_insertion_point(class_scope:protobuf.srl.action.Command)


# @@protoc_insertion_point(module_scope)
