// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: input/message.proto

package protobuf.srl.request;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .protobuf.srl.request.Request.MessageType requestType = 1 [default = LOGIN];
    /**
     * <code>required .protobuf.srl.request.Request.MessageType requestType = 1 [default = LOGIN];</code>
     */
    boolean hasRequestType();
    /**
     * <code>required .protobuf.srl.request.Request.MessageType requestType = 1 [default = LOGIN];</code>
     */
    protobuf.srl.request.Message.Request.MessageType getRequestType();

    // optional .protobuf.srl.request.LoginInformation login = 2;
    /**
     * <code>optional .protobuf.srl.request.LoginInformation login = 2;</code>
     */
    boolean hasLogin();
    /**
     * <code>optional .protobuf.srl.request.LoginInformation login = 2;</code>
     */
    protobuf.srl.request.Message.LoginInformation getLogin();
    /**
     * <code>optional .protobuf.srl.request.LoginInformation login = 2;</code>
     */
    protobuf.srl.request.Message.LoginInformationOrBuilder getLoginOrBuilder();

    // optional bytes otherData = 3;
    /**
     * <code>optional bytes otherData = 3;</code>
     */
    boolean hasOtherData();
    /**
     * <code>optional bytes otherData = 3;</code>
     */
    com.google.protobuf.ByteString getOtherData();

    // optional string responseText = 4;
    /**
     * <code>optional string responseText = 4;</code>
     */
    boolean hasResponseText();
    /**
     * <code>optional string responseText = 4;</code>
     */
    java.lang.String getResponseText();
    /**
     * <code>optional string responseText = 4;</code>
     */
    com.google.protobuf.ByteString
        getResponseTextBytes();

    // optional string sessionInfo = 5;
    /**
     * <code>optional string sessionInfo = 5;</code>
     *
     * <pre>
     * This may be separated out more.
     * </pre>
     */
    boolean hasSessionInfo();
    /**
     * <code>optional string sessionInfo = 5;</code>
     *
     * <pre>
     * This may be separated out more.
     * </pre>
     */
    java.lang.String getSessionInfo();
    /**
     * <code>optional string sessionInfo = 5;</code>
     *
     * <pre>
     * This may be separated out more.
     * </pre>
     */
    com.google.protobuf.ByteString
        getSessionInfoBytes();

    // optional string serversideId = 6;
    /**
     * <code>optional string serversideId = 6;</code>
     */
    boolean hasServersideId();
    /**
     * <code>optional string serversideId = 6;</code>
     */
    java.lang.String getServersideId();
    /**
     * <code>optional string serversideId = 6;</code>
     */
    com.google.protobuf.ByteString
        getServersideIdBytes();

    // optional int64 messageTime = 7;
    /**
     * <code>optional int64 messageTime = 7;</code>
     *
     * <pre>
     * this is the time that the message is received by the server
     * </pre>
     */
    boolean hasMessageTime();
    /**
     * <code>optional int64 messageTime = 7;</code>
     *
     * <pre>
     * this is the time that the message is received by the server
     * </pre>
     */
    long getMessageTime();
  }
  /**
   * Protobuf type {@code protobuf.srl.request.Request}
   *
   * <pre>
   * Always sent and is filled out properly.
   * </pre>
   */
  public static final class Request extends
      com.google.protobuf.GeneratedMessage
      implements RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }

    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              protobuf.srl.request.Message.Request.MessageType value = protobuf.srl.request.Message.Request.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                requestType_ = value;
              }
              break;
            }
            case 18: {
              protobuf.srl.request.Message.LoginInformation.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = login_.toBuilder();
              }
              login_ = input.readMessage(protobuf.srl.request.Message.LoginInformation.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(login_);
                login_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              otherData_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              responseText_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              sessionInfo_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              serversideId_ = input.readBytes();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              messageTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.srl.request.Message.internal_static_protobuf_srl_request_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.srl.request.Message.internal_static_protobuf_srl_request_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.srl.request.Message.Request.class, protobuf.srl.request.Message.Request.Builder.class);
    }

    public static com.google.protobuf.Parser<Request> PARSER =
        new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code protobuf.srl.request.Request.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>LOGIN = 0;</code>
       */
      LOGIN(0, 0),
      /**
       * <code>DATA_REQUEST = 1;</code>
       */
      DATA_REQUEST(1, 1),
      /**
       * <code>DATA_INSERT = 2;</code>
       */
      DATA_INSERT(2, 2),
      /**
       * <code>DATA_UPDATE = 3;</code>
       */
      DATA_UPDATE(3, 3),
      /**
       * <code>DATA_REMOVE = 4;</code>
       */
      DATA_REMOVE(4, 4),
      /**
       * <code>RECOGNITION = 5;</code>
       */
      RECOGNITION(5, 5),
      /**
       * <code>LOADING = 6;</code>
       *
       * <pre>
       * this is for when the client is loading.
       * </pre>
       */
      LOADING(6, 6),
      /**
       * <code>SUBMISSION = 7;</code>
       *
       * <pre>
       * sent to both servers at the same time. (Answer checking and database)
       * </pre>
       */
      SUBMISSION(7, 7),
      /**
       * <code>CLOSE = 8;</code>
       *
       * <pre>
       * sent to tell the server to close the connection rs
       * </pre>
       */
      CLOSE(8, 8),
      ;

      /**
       * <code>LOGIN = 0;</code>
       */
      public static final int LOGIN_VALUE = 0;
      /**
       * <code>DATA_REQUEST = 1;</code>
       */
      public static final int DATA_REQUEST_VALUE = 1;
      /**
       * <code>DATA_INSERT = 2;</code>
       */
      public static final int DATA_INSERT_VALUE = 2;
      /**
       * <code>DATA_UPDATE = 3;</code>
       */
      public static final int DATA_UPDATE_VALUE = 3;
      /**
       * <code>DATA_REMOVE = 4;</code>
       */
      public static final int DATA_REMOVE_VALUE = 4;
      /**
       * <code>RECOGNITION = 5;</code>
       */
      public static final int RECOGNITION_VALUE = 5;
      /**
       * <code>LOADING = 6;</code>
       *
       * <pre>
       * this is for when the client is loading.
       * </pre>
       */
      public static final int LOADING_VALUE = 6;
      /**
       * <code>SUBMISSION = 7;</code>
       *
       * <pre>
       * sent to both servers at the same time. (Answer checking and database)
       * </pre>
       */
      public static final int SUBMISSION_VALUE = 7;
      /**
       * <code>CLOSE = 8;</code>
       *
       * <pre>
       * sent to tell the server to close the connection rs
       * </pre>
       */
      public static final int CLOSE_VALUE = 8;


      public final int getNumber() { return value; }

      public static MessageType valueOf(int value) {
        switch (value) {
          case 0: return LOGIN;
          case 1: return DATA_REQUEST;
          case 2: return DATA_INSERT;
          case 3: return DATA_UPDATE;
          case 4: return DATA_REMOVE;
          case 5: return RECOGNITION;
          case 6: return LOADING;
          case 7: return SUBMISSION;
          case 8: return CLOSE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return protobuf.srl.request.Message.Request.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MessageType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protobuf.srl.request.Request.MessageType)
    }

    private int bitField0_;
    // required .protobuf.srl.request.Request.MessageType requestType = 1 [default = LOGIN];
    public static final int REQUESTTYPE_FIELD_NUMBER = 1;
    private protobuf.srl.request.Message.Request.MessageType requestType_;
    /**
     * <code>required .protobuf.srl.request.Request.MessageType requestType = 1 [default = LOGIN];</code>
     */
    public boolean hasRequestType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .protobuf.srl.request.Request.MessageType requestType = 1 [default = LOGIN];</code>
     */
    public protobuf.srl.request.Message.Request.MessageType getRequestType() {
      return requestType_;
    }

    // optional .protobuf.srl.request.LoginInformation login = 2;
    public static final int LOGIN_FIELD_NUMBER = 2;
    private protobuf.srl.request.Message.LoginInformation login_;
    /**
     * <code>optional .protobuf.srl.request.LoginInformation login = 2;</code>
     */
    public boolean hasLogin() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .protobuf.srl.request.LoginInformation login = 2;</code>
     */
    public protobuf.srl.request.Message.LoginInformation getLogin() {
      return login_;
    }
    /**
     * <code>optional .protobuf.srl.request.LoginInformation login = 2;</code>
     */
    public protobuf.srl.request.Message.LoginInformationOrBuilder getLoginOrBuilder() {
      return login_;
    }

    // optional bytes otherData = 3;
    public static final int OTHERDATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString otherData_;
    /**
     * <code>optional bytes otherData = 3;</code>
     */
    public boolean hasOtherData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes otherData = 3;</code>
     */
    public com.google.protobuf.ByteString getOtherData() {
      return otherData_;
    }

    // optional string responseText = 4;
    public static final int RESPONSETEXT_FIELD_NUMBER = 4;
    private java.lang.Object responseText_;
    /**
     * <code>optional string responseText = 4;</code>
     */
    public boolean hasResponseText() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string responseText = 4;</code>
     */
    public java.lang.String getResponseText() {
      java.lang.Object ref = responseText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          responseText_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string responseText = 4;</code>
     */
    public com.google.protobuf.ByteString
        getResponseTextBytes() {
      java.lang.Object ref = responseText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responseText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string sessionInfo = 5;
    public static final int SESSIONINFO_FIELD_NUMBER = 5;
    private java.lang.Object sessionInfo_;
    /**
     * <code>optional string sessionInfo = 5;</code>
     *
     * <pre>
     * This may be separated out more.
     * </pre>
     */
    public boolean hasSessionInfo() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string sessionInfo = 5;</code>
     *
     * <pre>
     * This may be separated out more.
     * </pre>
     */
    public java.lang.String getSessionInfo() {
      java.lang.Object ref = sessionInfo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sessionInfo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string sessionInfo = 5;</code>
     *
     * <pre>
     * This may be separated out more.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSessionInfoBytes() {
      java.lang.Object ref = sessionInfo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string serversideId = 6;
    public static final int SERVERSIDEID_FIELD_NUMBER = 6;
    private java.lang.Object serversideId_;
    /**
     * <code>optional string serversideId = 6;</code>
     */
    public boolean hasServersideId() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string serversideId = 6;</code>
     */
    public java.lang.String getServersideId() {
      java.lang.Object ref = serversideId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serversideId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string serversideId = 6;</code>
     */
    public com.google.protobuf.ByteString
        getServersideIdBytes() {
      java.lang.Object ref = serversideId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serversideId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int64 messageTime = 7;
    public static final int MESSAGETIME_FIELD_NUMBER = 7;
    private long messageTime_;
    /**
     * <code>optional int64 messageTime = 7;</code>
     *
     * <pre>
     * this is the time that the message is received by the server
     * </pre>
     */
    public boolean hasMessageTime() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int64 messageTime = 7;</code>
     *
     * <pre>
     * this is the time that the message is received by the server
     * </pre>
     */
    public long getMessageTime() {
      return messageTime_;
    }

    private void initFields() {
      requestType_ = protobuf.srl.request.Message.Request.MessageType.LOGIN;
      login_ = protobuf.srl.request.Message.LoginInformation.getDefaultInstance();
      otherData_ = com.google.protobuf.ByteString.EMPTY;
      responseText_ = "";
      sessionInfo_ = "";
      serversideId_ = "";
      messageTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRequestType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasLogin()) {
        if (!getLogin().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, requestType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, login_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, otherData_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getResponseTextBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getSessionInfoBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getServersideIdBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt64(7, messageTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, requestType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, login_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, otherData_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getResponseTextBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getSessionInfoBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getServersideIdBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, messageTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.srl.request.Message.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.srl.request.Message.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.srl.request.Message.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.srl.request.Message.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.srl.request.Message.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.srl.request.Message.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.srl.request.Message.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.srl.request.Message.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.srl.request.Message.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.srl.request.Message.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.srl.request.Message.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.srl.request.Request}
     *
     * <pre>
     * Always sent and is filled out properly.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.srl.request.Message.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.srl.request.Message.internal_static_protobuf_srl_request_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.srl.request.Message.internal_static_protobuf_srl_request_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.srl.request.Message.Request.class, protobuf.srl.request.Message.Request.Builder.class);
      }

      // Construct using protobuf.srl.request.Message.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getLoginFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        requestType_ = protobuf.srl.request.Message.Request.MessageType.LOGIN;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (loginBuilder_ == null) {
          login_ = protobuf.srl.request.Message.LoginInformation.getDefaultInstance();
        } else {
          loginBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        otherData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        responseText_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        sessionInfo_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        serversideId_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        messageTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.srl.request.Message.internal_static_protobuf_srl_request_Request_descriptor;
      }

      public protobuf.srl.request.Message.Request getDefaultInstanceForType() {
        return protobuf.srl.request.Message.Request.getDefaultInstance();
      }

      public protobuf.srl.request.Message.Request build() {
        protobuf.srl.request.Message.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.srl.request.Message.Request buildPartial() {
        protobuf.srl.request.Message.Request result = new protobuf.srl.request.Message.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.requestType_ = requestType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (loginBuilder_ == null) {
          result.login_ = login_;
        } else {
          result.login_ = loginBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.otherData_ = otherData_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.responseText_ = responseText_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.sessionInfo_ = sessionInfo_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.serversideId_ = serversideId_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.messageTime_ = messageTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.srl.request.Message.Request) {
          return mergeFrom((protobuf.srl.request.Message.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.srl.request.Message.Request other) {
        if (other == protobuf.srl.request.Message.Request.getDefaultInstance()) return this;
        if (other.hasRequestType()) {
          setRequestType(other.getRequestType());
        }
        if (other.hasLogin()) {
          mergeLogin(other.getLogin());
        }
        if (other.hasOtherData()) {
          setOtherData(other.getOtherData());
        }
        if (other.hasResponseText()) {
          bitField0_ |= 0x00000008;
          responseText_ = other.responseText_;
          onChanged();
        }
        if (other.hasSessionInfo()) {
          bitField0_ |= 0x00000010;
          sessionInfo_ = other.sessionInfo_;
          onChanged();
        }
        if (other.hasServersideId()) {
          bitField0_ |= 0x00000020;
          serversideId_ = other.serversideId_;
          onChanged();
        }
        if (other.hasMessageTime()) {
          setMessageTime(other.getMessageTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRequestType()) {
          
          return false;
        }
        if (hasLogin()) {
          if (!getLogin().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.srl.request.Message.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.srl.request.Message.Request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .protobuf.srl.request.Request.MessageType requestType = 1 [default = LOGIN];
      private protobuf.srl.request.Message.Request.MessageType requestType_ = protobuf.srl.request.Message.Request.MessageType.LOGIN;
      /**
       * <code>required .protobuf.srl.request.Request.MessageType requestType = 1 [default = LOGIN];</code>
       */
      public boolean hasRequestType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .protobuf.srl.request.Request.MessageType requestType = 1 [default = LOGIN];</code>
       */
      public protobuf.srl.request.Message.Request.MessageType getRequestType() {
        return requestType_;
      }
      /**
       * <code>required .protobuf.srl.request.Request.MessageType requestType = 1 [default = LOGIN];</code>
       */
      public Builder setRequestType(protobuf.srl.request.Message.Request.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        requestType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .protobuf.srl.request.Request.MessageType requestType = 1 [default = LOGIN];</code>
       */
      public Builder clearRequestType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        requestType_ = protobuf.srl.request.Message.Request.MessageType.LOGIN;
        onChanged();
        return this;
      }

      // optional .protobuf.srl.request.LoginInformation login = 2;
      private protobuf.srl.request.Message.LoginInformation login_ = protobuf.srl.request.Message.LoginInformation.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          protobuf.srl.request.Message.LoginInformation, protobuf.srl.request.Message.LoginInformation.Builder, protobuf.srl.request.Message.LoginInformationOrBuilder> loginBuilder_;
      /**
       * <code>optional .protobuf.srl.request.LoginInformation login = 2;</code>
       */
      public boolean hasLogin() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .protobuf.srl.request.LoginInformation login = 2;</code>
       */
      public protobuf.srl.request.Message.LoginInformation getLogin() {
        if (loginBuilder_ == null) {
          return login_;
        } else {
          return loginBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .protobuf.srl.request.LoginInformation login = 2;</code>
       */
      public Builder setLogin(protobuf.srl.request.Message.LoginInformation value) {
        if (loginBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          login_ = value;
          onChanged();
        } else {
          loginBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .protobuf.srl.request.LoginInformation login = 2;</code>
       */
      public Builder setLogin(
          protobuf.srl.request.Message.LoginInformation.Builder builderForValue) {
        if (loginBuilder_ == null) {
          login_ = builderForValue.build();
          onChanged();
        } else {
          loginBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .protobuf.srl.request.LoginInformation login = 2;</code>
       */
      public Builder mergeLogin(protobuf.srl.request.Message.LoginInformation value) {
        if (loginBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              login_ != protobuf.srl.request.Message.LoginInformation.getDefaultInstance()) {
            login_ =
              protobuf.srl.request.Message.LoginInformation.newBuilder(login_).mergeFrom(value).buildPartial();
          } else {
            login_ = value;
          }
          onChanged();
        } else {
          loginBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .protobuf.srl.request.LoginInformation login = 2;</code>
       */
      public Builder clearLogin() {
        if (loginBuilder_ == null) {
          login_ = protobuf.srl.request.Message.LoginInformation.getDefaultInstance();
          onChanged();
        } else {
          loginBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .protobuf.srl.request.LoginInformation login = 2;</code>
       */
      public protobuf.srl.request.Message.LoginInformation.Builder getLoginBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getLoginFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .protobuf.srl.request.LoginInformation login = 2;</code>
       */
      public protobuf.srl.request.Message.LoginInformationOrBuilder getLoginOrBuilder() {
        if (loginBuilder_ != null) {
          return loginBuilder_.getMessageOrBuilder();
        } else {
          return login_;
        }
      }
      /**
       * <code>optional .protobuf.srl.request.LoginInformation login = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          protobuf.srl.request.Message.LoginInformation, protobuf.srl.request.Message.LoginInformation.Builder, protobuf.srl.request.Message.LoginInformationOrBuilder> 
          getLoginFieldBuilder() {
        if (loginBuilder_ == null) {
          loginBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              protobuf.srl.request.Message.LoginInformation, protobuf.srl.request.Message.LoginInformation.Builder, protobuf.srl.request.Message.LoginInformationOrBuilder>(
                  login_,
                  getParentForChildren(),
                  isClean());
          login_ = null;
        }
        return loginBuilder_;
      }

      // optional bytes otherData = 3;
      private com.google.protobuf.ByteString otherData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes otherData = 3;</code>
       */
      public boolean hasOtherData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes otherData = 3;</code>
       */
      public com.google.protobuf.ByteString getOtherData() {
        return otherData_;
      }
      /**
       * <code>optional bytes otherData = 3;</code>
       */
      public Builder setOtherData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        otherData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes otherData = 3;</code>
       */
      public Builder clearOtherData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        otherData_ = getDefaultInstance().getOtherData();
        onChanged();
        return this;
      }

      // optional string responseText = 4;
      private java.lang.Object responseText_ = "";
      /**
       * <code>optional string responseText = 4;</code>
       */
      public boolean hasResponseText() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string responseText = 4;</code>
       */
      public java.lang.String getResponseText() {
        java.lang.Object ref = responseText_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          responseText_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string responseText = 4;</code>
       */
      public com.google.protobuf.ByteString
          getResponseTextBytes() {
        java.lang.Object ref = responseText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          responseText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string responseText = 4;</code>
       */
      public Builder setResponseText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        responseText_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string responseText = 4;</code>
       */
      public Builder clearResponseText() {
        bitField0_ = (bitField0_ & ~0x00000008);
        responseText_ = getDefaultInstance().getResponseText();
        onChanged();
        return this;
      }
      /**
       * <code>optional string responseText = 4;</code>
       */
      public Builder setResponseTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        responseText_ = value;
        onChanged();
        return this;
      }

      // optional string sessionInfo = 5;
      private java.lang.Object sessionInfo_ = "";
      /**
       * <code>optional string sessionInfo = 5;</code>
       *
       * <pre>
       * This may be separated out more.
       * </pre>
       */
      public boolean hasSessionInfo() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string sessionInfo = 5;</code>
       *
       * <pre>
       * This may be separated out more.
       * </pre>
       */
      public java.lang.String getSessionInfo() {
        java.lang.Object ref = sessionInfo_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sessionInfo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sessionInfo = 5;</code>
       *
       * <pre>
       * This may be separated out more.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getSessionInfoBytes() {
        java.lang.Object ref = sessionInfo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sessionInfo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sessionInfo = 5;</code>
       *
       * <pre>
       * This may be separated out more.
       * </pre>
       */
      public Builder setSessionInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        sessionInfo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sessionInfo = 5;</code>
       *
       * <pre>
       * This may be separated out more.
       * </pre>
       */
      public Builder clearSessionInfo() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sessionInfo_ = getDefaultInstance().getSessionInfo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sessionInfo = 5;</code>
       *
       * <pre>
       * This may be separated out more.
       * </pre>
       */
      public Builder setSessionInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        sessionInfo_ = value;
        onChanged();
        return this;
      }

      // optional string serversideId = 6;
      private java.lang.Object serversideId_ = "";
      /**
       * <code>optional string serversideId = 6;</code>
       */
      public boolean hasServersideId() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string serversideId = 6;</code>
       */
      public java.lang.String getServersideId() {
        java.lang.Object ref = serversideId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          serversideId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string serversideId = 6;</code>
       */
      public com.google.protobuf.ByteString
          getServersideIdBytes() {
        java.lang.Object ref = serversideId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serversideId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string serversideId = 6;</code>
       */
      public Builder setServersideId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        serversideId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string serversideId = 6;</code>
       */
      public Builder clearServersideId() {
        bitField0_ = (bitField0_ & ~0x00000020);
        serversideId_ = getDefaultInstance().getServersideId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string serversideId = 6;</code>
       */
      public Builder setServersideIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        serversideId_ = value;
        onChanged();
        return this;
      }

      // optional int64 messageTime = 7;
      private long messageTime_ ;
      /**
       * <code>optional int64 messageTime = 7;</code>
       *
       * <pre>
       * this is the time that the message is received by the server
       * </pre>
       */
      public boolean hasMessageTime() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int64 messageTime = 7;</code>
       *
       * <pre>
       * this is the time that the message is received by the server
       * </pre>
       */
      public long getMessageTime() {
        return messageTime_;
      }
      /**
       * <code>optional int64 messageTime = 7;</code>
       *
       * <pre>
       * this is the time that the message is received by the server
       * </pre>
       */
      public Builder setMessageTime(long value) {
        bitField0_ |= 0x00000040;
        messageTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 messageTime = 7;</code>
       *
       * <pre>
       * this is the time that the message is received by the server
       * </pre>
       */
      public Builder clearMessageTime() {
        bitField0_ = (bitField0_ & ~0x00000040);
        messageTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.srl.request.Request)
    }

    static {
      defaultInstance = new Request(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.srl.request.Request)
  }

  public interface LoginInformationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string username = 1;
    /**
     * <code>required string username = 1;</code>
     */
    boolean hasUsername();
    /**
     * <code>required string username = 1;</code>
     */
    java.lang.String getUsername();
    /**
     * <code>required string username = 1;</code>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    // optional string password = 2;
    /**
     * <code>optional string password = 2;</code>
     */
    boolean hasPassword();
    /**
     * <code>optional string password = 2;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>optional string password = 2;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    // optional bool isLoggedIn = 3;
    /**
     * <code>optional bool isLoggedIn = 3;</code>
     */
    boolean hasIsLoggedIn();
    /**
     * <code>optional bool isLoggedIn = 3;</code>
     */
    boolean getIsLoggedIn();

    // optional bool isInstructor = 4;
    /**
     * <code>optional bool isInstructor = 4;</code>
     */
    boolean hasIsInstructor();
    /**
     * <code>optional bool isInstructor = 4;</code>
     */
    boolean getIsInstructor();

    // optional bool isRegistering = 5;
    /**
     * <code>optional bool isRegistering = 5;</code>
     */
    boolean hasIsRegistering();
    /**
     * <code>optional bool isRegistering = 5;</code>
     */
    boolean getIsRegistering();

    // optional string email = 6;
    /**
     * <code>optional string email = 6;</code>
     */
    boolean hasEmail();
    /**
     * <code>optional string email = 6;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>optional string email = 6;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    // optional string userId = 7;
    /**
     * <code>optional string userId = 7;</code>
     */
    boolean hasUserId();
    /**
     * <code>optional string userId = 7;</code>
     */
    java.lang.String getUserId();
    /**
     * <code>optional string userId = 7;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();
  }
  /**
   * Protobuf type {@code protobuf.srl.request.LoginInformation}
   */
  public static final class LoginInformation extends
      com.google.protobuf.GeneratedMessage
      implements LoginInformationOrBuilder {
    // Use LoginInformation.newBuilder() to construct.
    private LoginInformation(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LoginInformation(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LoginInformation defaultInstance;
    public static LoginInformation getDefaultInstance() {
      return defaultInstance;
    }

    public LoginInformation getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LoginInformation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              username_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              password_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              isLoggedIn_ = input.readBool();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              isInstructor_ = input.readBool();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              isRegistering_ = input.readBool();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              email_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              userId_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.srl.request.Message.internal_static_protobuf_srl_request_LoginInformation_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.srl.request.Message.internal_static_protobuf_srl_request_LoginInformation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.srl.request.Message.LoginInformation.class, protobuf.srl.request.Message.LoginInformation.Builder.class);
    }

    public static com.google.protobuf.Parser<LoginInformation> PARSER =
        new com.google.protobuf.AbstractParser<LoginInformation>() {
      public LoginInformation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginInformation(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LoginInformation> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string username = 1;
    public static final int USERNAME_FIELD_NUMBER = 1;
    private java.lang.Object username_;
    /**
     * <code>required string username = 1;</code>
     */
    public boolean hasUsername() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string username = 1;</code>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          username_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string username = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string password = 2;
    public static final int PASSWORD_FIELD_NUMBER = 2;
    private java.lang.Object password_;
    /**
     * <code>optional string password = 2;</code>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string password = 2;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string password = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bool isLoggedIn = 3;
    public static final int ISLOGGEDIN_FIELD_NUMBER = 3;
    private boolean isLoggedIn_;
    /**
     * <code>optional bool isLoggedIn = 3;</code>
     */
    public boolean hasIsLoggedIn() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bool isLoggedIn = 3;</code>
     */
    public boolean getIsLoggedIn() {
      return isLoggedIn_;
    }

    // optional bool isInstructor = 4;
    public static final int ISINSTRUCTOR_FIELD_NUMBER = 4;
    private boolean isInstructor_;
    /**
     * <code>optional bool isInstructor = 4;</code>
     */
    public boolean hasIsInstructor() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bool isInstructor = 4;</code>
     */
    public boolean getIsInstructor() {
      return isInstructor_;
    }

    // optional bool isRegistering = 5;
    public static final int ISREGISTERING_FIELD_NUMBER = 5;
    private boolean isRegistering_;
    /**
     * <code>optional bool isRegistering = 5;</code>
     */
    public boolean hasIsRegistering() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bool isRegistering = 5;</code>
     */
    public boolean getIsRegistering() {
      return isRegistering_;
    }

    // optional string email = 6;
    public static final int EMAIL_FIELD_NUMBER = 6;
    private java.lang.Object email_;
    /**
     * <code>optional string email = 6;</code>
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string email = 6;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          email_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string email = 6;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string userId = 7;
    public static final int USERID_FIELD_NUMBER = 7;
    private java.lang.Object userId_;
    /**
     * <code>optional string userId = 7;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string userId = 7;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string userId = 7;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      username_ = "";
      password_ = "";
      isLoggedIn_ = false;
      isInstructor_ = false;
      isRegistering_ = false;
      email_ = "";
      userId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUsername()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, isLoggedIn_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, isInstructor_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, isRegistering_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getEmailBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getUserIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isLoggedIn_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, isInstructor_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, isRegistering_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getEmailBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getUserIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.srl.request.Message.LoginInformation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.srl.request.Message.LoginInformation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.srl.request.Message.LoginInformation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.srl.request.Message.LoginInformation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.srl.request.Message.LoginInformation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.srl.request.Message.LoginInformation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.srl.request.Message.LoginInformation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.srl.request.Message.LoginInformation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.srl.request.Message.LoginInformation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.srl.request.Message.LoginInformation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.srl.request.Message.LoginInformation prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.srl.request.LoginInformation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.srl.request.Message.LoginInformationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.srl.request.Message.internal_static_protobuf_srl_request_LoginInformation_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.srl.request.Message.internal_static_protobuf_srl_request_LoginInformation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.srl.request.Message.LoginInformation.class, protobuf.srl.request.Message.LoginInformation.Builder.class);
      }

      // Construct using protobuf.srl.request.Message.LoginInformation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        username_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        isLoggedIn_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        isInstructor_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        isRegistering_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        userId_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.srl.request.Message.internal_static_protobuf_srl_request_LoginInformation_descriptor;
      }

      public protobuf.srl.request.Message.LoginInformation getDefaultInstanceForType() {
        return protobuf.srl.request.Message.LoginInformation.getDefaultInstance();
      }

      public protobuf.srl.request.Message.LoginInformation build() {
        protobuf.srl.request.Message.LoginInformation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.srl.request.Message.LoginInformation buildPartial() {
        protobuf.srl.request.Message.LoginInformation result = new protobuf.srl.request.Message.LoginInformation(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.username_ = username_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.password_ = password_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.isLoggedIn_ = isLoggedIn_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.isInstructor_ = isInstructor_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.isRegistering_ = isRegistering_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.email_ = email_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.userId_ = userId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.srl.request.Message.LoginInformation) {
          return mergeFrom((protobuf.srl.request.Message.LoginInformation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.srl.request.Message.LoginInformation other) {
        if (other == protobuf.srl.request.Message.LoginInformation.getDefaultInstance()) return this;
        if (other.hasUsername()) {
          bitField0_ |= 0x00000001;
          username_ = other.username_;
          onChanged();
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000002;
          password_ = other.password_;
          onChanged();
        }
        if (other.hasIsLoggedIn()) {
          setIsLoggedIn(other.getIsLoggedIn());
        }
        if (other.hasIsInstructor()) {
          setIsInstructor(other.getIsInstructor());
        }
        if (other.hasIsRegistering()) {
          setIsRegistering(other.getIsRegistering());
        }
        if (other.hasEmail()) {
          bitField0_ |= 0x00000020;
          email_ = other.email_;
          onChanged();
        }
        if (other.hasUserId()) {
          bitField0_ |= 0x00000040;
          userId_ = other.userId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUsername()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.srl.request.Message.LoginInformation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.srl.request.Message.LoginInformation) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string username = 1;
      private java.lang.Object username_ = "";
      /**
       * <code>required string username = 1;</code>
       */
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string username = 1;</code>
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string username = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string username = 1;</code>
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string username = 1;</code>
       */
      public Builder clearUsername() {
        bitField0_ = (bitField0_ & ~0x00000001);
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <code>required string username = 1;</code>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        username_ = value;
        onChanged();
        return this;
      }

      // optional string password = 2;
      private java.lang.Object password_ = "";
      /**
       * <code>optional string password = 2;</code>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }

      // optional bool isLoggedIn = 3;
      private boolean isLoggedIn_ ;
      /**
       * <code>optional bool isLoggedIn = 3;</code>
       */
      public boolean hasIsLoggedIn() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bool isLoggedIn = 3;</code>
       */
      public boolean getIsLoggedIn() {
        return isLoggedIn_;
      }
      /**
       * <code>optional bool isLoggedIn = 3;</code>
       */
      public Builder setIsLoggedIn(boolean value) {
        bitField0_ |= 0x00000004;
        isLoggedIn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool isLoggedIn = 3;</code>
       */
      public Builder clearIsLoggedIn() {
        bitField0_ = (bitField0_ & ~0x00000004);
        isLoggedIn_ = false;
        onChanged();
        return this;
      }

      // optional bool isInstructor = 4;
      private boolean isInstructor_ ;
      /**
       * <code>optional bool isInstructor = 4;</code>
       */
      public boolean hasIsInstructor() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bool isInstructor = 4;</code>
       */
      public boolean getIsInstructor() {
        return isInstructor_;
      }
      /**
       * <code>optional bool isInstructor = 4;</code>
       */
      public Builder setIsInstructor(boolean value) {
        bitField0_ |= 0x00000008;
        isInstructor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool isInstructor = 4;</code>
       */
      public Builder clearIsInstructor() {
        bitField0_ = (bitField0_ & ~0x00000008);
        isInstructor_ = false;
        onChanged();
        return this;
      }

      // optional bool isRegistering = 5;
      private boolean isRegistering_ ;
      /**
       * <code>optional bool isRegistering = 5;</code>
       */
      public boolean hasIsRegistering() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bool isRegistering = 5;</code>
       */
      public boolean getIsRegistering() {
        return isRegistering_;
      }
      /**
       * <code>optional bool isRegistering = 5;</code>
       */
      public Builder setIsRegistering(boolean value) {
        bitField0_ |= 0x00000010;
        isRegistering_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool isRegistering = 5;</code>
       */
      public Builder clearIsRegistering() {
        bitField0_ = (bitField0_ & ~0x00000010);
        isRegistering_ = false;
        onChanged();
        return this;
      }

      // optional string email = 6;
      private java.lang.Object email_ = "";
      /**
       * <code>optional string email = 6;</code>
       */
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string email = 6;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string email = 6;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string email = 6;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 6;</code>
       */
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000020);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 6;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        email_ = value;
        onChanged();
        return this;
      }

      // optional string userId = 7;
      private java.lang.Object userId_ = "";
      /**
       * <code>optional string userId = 7;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string userId = 7;</code>
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userId = 7;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userId = 7;</code>
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userId = 7;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000040);
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userId = 7;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        userId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.srl.request.LoginInformation)
    }

    static {
      defaultInstance = new LoginInformation(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.srl.request.LoginInformation)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_srl_request_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_srl_request_Request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_srl_request_LoginInformation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_srl_request_LoginInformation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023input/message.proto\022\024protobuf.srl.requ" +
      "est\"\211\003\n\007Request\022E\n\013requestType\030\001 \002(\0162).p" +
      "rotobuf.srl.request.Request.MessageType:" +
      "\005LOGIN\0225\n\005login\030\002 \001(\0132&.protobuf.srl.req" +
      "uest.LoginInformation\022\021\n\totherData\030\003 \001(\014" +
      "\022\024\n\014responseText\030\004 \001(\t\022\023\n\013sessionInfo\030\005 " +
      "\001(\t\022\024\n\014serversideId\030\006 \001(\t\022\023\n\013messageTime" +
      "\030\007 \001(\003\"\226\001\n\013MessageType\022\t\n\005LOGIN\020\000\022\020\n\014DAT" +
      "A_REQUEST\020\001\022\017\n\013DATA_INSERT\020\002\022\017\n\013DATA_UPD" +
      "ATE\020\003\022\017\n\013DATA_REMOVE\020\004\022\017\n\013RECOGNITION\020\005\022",
      "\013\n\007LOADING\020\006\022\016\n\nSUBMISSION\020\007\022\t\n\005CLOSE\020\010\"" +
      "\226\001\n\020LoginInformation\022\020\n\010username\030\001 \002(\t\022\020" +
      "\n\010password\030\002 \001(\t\022\022\n\nisLoggedIn\030\003 \001(\010\022\024\n\014" +
      "isInstructor\030\004 \001(\010\022\025\n\risRegistering\030\005 \001(" +
      "\010\022\r\n\005email\030\006 \001(\t\022\016\n\006userId\030\007 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protobuf_srl_request_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protobuf_srl_request_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_srl_request_Request_descriptor,
              new java.lang.String[] { "RequestType", "Login", "OtherData", "ResponseText", "SessionInfo", "ServersideId", "MessageTime", });
          internal_static_protobuf_srl_request_LoginInformation_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protobuf_srl_request_LoginInformation_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_srl_request_LoginInformation_descriptor,
              new java.lang.String[] { "Username", "Password", "IsLoggedIn", "IsInstructor", "IsRegistering", "Email", "UserId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
