#starts off with dev so that we can differntiate in app engine.  As app engine cuts words off.
application: dev-coursesketch
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  script: testFiles.app

- url: /index\.html
  static_files: index.html
  upload: index\.html

- url: /testList
  script: testFiles.app

- url: /html
  static_dir: src/html

- url: /js
  static_dir: src/js

- url: /css
  static_dir: src/main/resources/css

- url: /src/test/src
  static_dir: src/test/src
  application_readable: true

- url: /src
  static_dir: src/main/src

- url: /test
  static_dir: src/test/src
  application_readable: true

- url: /images
  static_dir: src/main/resources/images

- url: /other
  static_dir: src/main/resources/other

- url: /*
  script: testFiles.app

- url: /bower_components
  static_dir: bower_components
