// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: input/action.proto

package protobuf.srl.action;

public final class Action {
  private Action() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code protobuf.srl.action.CommandType}
   */
  public enum CommandType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ADD_STROKE = 0;</code>
     *
     * <pre>
     * This will only contain a SRL_Stroke in commandData
     * </pre>
     */
    ADD_STROKE(0, 0),
    /**
     * <code>ADD_SHAPE = 1;</code>
     *
     * <pre>
     * contains a shape.
     * </pre>
     */
    ADD_SHAPE(1, 1),
    /**
     * <code>REPACKAGE_SHAPE = 2;</code>
     *
     * <pre>
     * repackages shapes from the surface to inside another shape
     * </pre>
     */
    REPACKAGE_SHAPE(2, 2),
    /**
     * <code>FORCE_INTERPRETATION = 3;</code>
     */
    FORCE_INTERPRETATION(3, 3),
    ;

    /**
     * <code>ADD_STROKE = 0;</code>
     *
     * <pre>
     * This will only contain a SRL_Stroke in commandData
     * </pre>
     */
    public static final int ADD_STROKE_VALUE = 0;
    /**
     * <code>ADD_SHAPE = 1;</code>
     *
     * <pre>
     * contains a shape.
     * </pre>
     */
    public static final int ADD_SHAPE_VALUE = 1;
    /**
     * <code>REPACKAGE_SHAPE = 2;</code>
     *
     * <pre>
     * repackages shapes from the surface to inside another shape
     * </pre>
     */
    public static final int REPACKAGE_SHAPE_VALUE = 2;
    /**
     * <code>FORCE_INTERPRETATION = 3;</code>
     */
    public static final int FORCE_INTERPRETATION_VALUE = 3;


    public final int getNumber() { return value; }

    public static CommandType valueOf(int value) {
      switch (value) {
        case 0: return ADD_STROKE;
        case 1: return ADD_SHAPE;
        case 2: return REPACKAGE_SHAPE;
        case 3: return FORCE_INTERPRETATION;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CommandType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<CommandType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CommandType>() {
            public CommandType findValueByNumber(int number) {
              return CommandType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return protobuf.srl.action.Action.getDescriptor().getEnumTypes().get(0);
    }

    private static final CommandType[] VALUES = values();

    public static CommandType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private CommandType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:protobuf.srl.action.CommandType)
  }

  public interface UpdateOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .protobuf.srl.action.Command commands = 1;
    /**
     * <code>repeated .protobuf.srl.action.Command commands = 1;</code>
     */
    java.util.List<protobuf.srl.action.Action.Command> 
        getCommandsList();
    /**
     * <code>repeated .protobuf.srl.action.Command commands = 1;</code>
     */
    protobuf.srl.action.Action.Command getCommands(int index);
    /**
     * <code>repeated .protobuf.srl.action.Command commands = 1;</code>
     */
    int getCommandsCount();
    /**
     * <code>repeated .protobuf.srl.action.Command commands = 1;</code>
     */
    java.util.List<? extends protobuf.srl.action.Action.CommandOrBuilder> 
        getCommandsOrBuilderList();
    /**
     * <code>repeated .protobuf.srl.action.Command commands = 1;</code>
     */
    protobuf.srl.action.Action.CommandOrBuilder getCommandsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protobuf.srl.action.Update}
   */
  public static final class Update extends
      com.google.protobuf.GeneratedMessage
      implements UpdateOrBuilder {
    // Use Update.newBuilder() to construct.
    private Update(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Update(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Update defaultInstance;
    public static Update getDefaultInstance() {
      return defaultInstance;
    }

    public Update getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Update(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                commands_ = new java.util.ArrayList<protobuf.srl.action.Action.Command>();
                mutable_bitField0_ |= 0x00000001;
              }
              commands_.add(input.readMessage(protobuf.srl.action.Action.Command.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          commands_ = java.util.Collections.unmodifiableList(commands_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.srl.action.Action.internal_static_protobuf_srl_action_Update_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.srl.action.Action.internal_static_protobuf_srl_action_Update_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.srl.action.Action.Update.class, protobuf.srl.action.Action.Update.Builder.class);
    }

    public static com.google.protobuf.Parser<Update> PARSER =
        new com.google.protobuf.AbstractParser<Update>() {
      public Update parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Update(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Update> getParserForType() {
      return PARSER;
    }

    // repeated .protobuf.srl.action.Command commands = 1;
    public static final int COMMANDS_FIELD_NUMBER = 1;
    private java.util.List<protobuf.srl.action.Action.Command> commands_;
    /**
     * <code>repeated .protobuf.srl.action.Command commands = 1;</code>
     */
    public java.util.List<protobuf.srl.action.Action.Command> getCommandsList() {
      return commands_;
    }
    /**
     * <code>repeated .protobuf.srl.action.Command commands = 1;</code>
     */
    public java.util.List<? extends protobuf.srl.action.Action.CommandOrBuilder> 
        getCommandsOrBuilderList() {
      return commands_;
    }
    /**
     * <code>repeated .protobuf.srl.action.Command commands = 1;</code>
     */
    public int getCommandsCount() {
      return commands_.size();
    }
    /**
     * <code>repeated .protobuf.srl.action.Command commands = 1;</code>
     */
    public protobuf.srl.action.Action.Command getCommands(int index) {
      return commands_.get(index);
    }
    /**
     * <code>repeated .protobuf.srl.action.Command commands = 1;</code>
     */
    public protobuf.srl.action.Action.CommandOrBuilder getCommandsOrBuilder(
        int index) {
      return commands_.get(index);
    }

    private void initFields() {
      commands_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getCommandsCount(); i++) {
        if (!getCommands(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < commands_.size(); i++) {
        output.writeMessage(1, commands_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < commands_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, commands_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.srl.action.Action.Update parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.srl.action.Action.Update parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.srl.action.Action.Update parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.srl.action.Action.Update parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.srl.action.Action.Update parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.srl.action.Action.Update parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.srl.action.Action.Update parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.srl.action.Action.Update parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.srl.action.Action.Update parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.srl.action.Action.Update parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.srl.action.Action.Update prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.srl.action.Update}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.srl.action.Action.UpdateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.srl.action.Action.internal_static_protobuf_srl_action_Update_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.srl.action.Action.internal_static_protobuf_srl_action_Update_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.srl.action.Action.Update.class, protobuf.srl.action.Action.Update.Builder.class);
      }

      // Construct using protobuf.srl.action.Action.Update.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCommandsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (commandsBuilder_ == null) {
          commands_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          commandsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.srl.action.Action.internal_static_protobuf_srl_action_Update_descriptor;
      }

      public protobuf.srl.action.Action.Update getDefaultInstanceForType() {
        return protobuf.srl.action.Action.Update.getDefaultInstance();
      }

      public protobuf.srl.action.Action.Update build() {
        protobuf.srl.action.Action.Update result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.srl.action.Action.Update buildPartial() {
        protobuf.srl.action.Action.Update result = new protobuf.srl.action.Action.Update(this);
        int from_bitField0_ = bitField0_;
        if (commandsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            commands_ = java.util.Collections.unmodifiableList(commands_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.commands_ = commands_;
        } else {
          result.commands_ = commandsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.srl.action.Action.Update) {
          return mergeFrom((protobuf.srl.action.Action.Update)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.srl.action.Action.Update other) {
        if (other == protobuf.srl.action.Action.Update.getDefaultInstance()) return this;
        if (commandsBuilder_ == null) {
          if (!other.commands_.isEmpty()) {
            if (commands_.isEmpty()) {
              commands_ = other.commands_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCommandsIsMutable();
              commands_.addAll(other.commands_);
            }
            onChanged();
          }
        } else {
          if (!other.commands_.isEmpty()) {
            if (commandsBuilder_.isEmpty()) {
              commandsBuilder_.dispose();
              commandsBuilder_ = null;
              commands_ = other.commands_;
              bitField0_ = (bitField0_ & ~0x00000001);
              commandsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getCommandsFieldBuilder() : null;
            } else {
              commandsBuilder_.addAllMessages(other.commands_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getCommandsCount(); i++) {
          if (!getCommands(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.srl.action.Action.Update parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.srl.action.Action.Update) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .protobuf.srl.action.Command commands = 1;
      private java.util.List<protobuf.srl.action.Action.Command> commands_ =
        java.util.Collections.emptyList();
      private void ensureCommandsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          commands_ = new java.util.ArrayList<protobuf.srl.action.Action.Command>(commands_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          protobuf.srl.action.Action.Command, protobuf.srl.action.Action.Command.Builder, protobuf.srl.action.Action.CommandOrBuilder> commandsBuilder_;

      /**
       * <code>repeated .protobuf.srl.action.Command commands = 1;</code>
       */
      public java.util.List<protobuf.srl.action.Action.Command> getCommandsList() {
        if (commandsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(commands_);
        } else {
          return commandsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protobuf.srl.action.Command commands = 1;</code>
       */
      public int getCommandsCount() {
        if (commandsBuilder_ == null) {
          return commands_.size();
        } else {
          return commandsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protobuf.srl.action.Command commands = 1;</code>
       */
      public protobuf.srl.action.Action.Command getCommands(int index) {
        if (commandsBuilder_ == null) {
          return commands_.get(index);
        } else {
          return commandsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protobuf.srl.action.Command commands = 1;</code>
       */
      public Builder setCommands(
          int index, protobuf.srl.action.Action.Command value) {
        if (commandsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCommandsIsMutable();
          commands_.set(index, value);
          onChanged();
        } else {
          commandsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.srl.action.Command commands = 1;</code>
       */
      public Builder setCommands(
          int index, protobuf.srl.action.Action.Command.Builder builderForValue) {
        if (commandsBuilder_ == null) {
          ensureCommandsIsMutable();
          commands_.set(index, builderForValue.build());
          onChanged();
        } else {
          commandsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.srl.action.Command commands = 1;</code>
       */
      public Builder addCommands(protobuf.srl.action.Action.Command value) {
        if (commandsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCommandsIsMutable();
          commands_.add(value);
          onChanged();
        } else {
          commandsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.srl.action.Command commands = 1;</code>
       */
      public Builder addCommands(
          int index, protobuf.srl.action.Action.Command value) {
        if (commandsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCommandsIsMutable();
          commands_.add(index, value);
          onChanged();
        } else {
          commandsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.srl.action.Command commands = 1;</code>
       */
      public Builder addCommands(
          protobuf.srl.action.Action.Command.Builder builderForValue) {
        if (commandsBuilder_ == null) {
          ensureCommandsIsMutable();
          commands_.add(builderForValue.build());
          onChanged();
        } else {
          commandsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.srl.action.Command commands = 1;</code>
       */
      public Builder addCommands(
          int index, protobuf.srl.action.Action.Command.Builder builderForValue) {
        if (commandsBuilder_ == null) {
          ensureCommandsIsMutable();
          commands_.add(index, builderForValue.build());
          onChanged();
        } else {
          commandsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.srl.action.Command commands = 1;</code>
       */
      public Builder addAllCommands(
          java.lang.Iterable<? extends protobuf.srl.action.Action.Command> values) {
        if (commandsBuilder_ == null) {
          ensureCommandsIsMutable();
          super.addAll(values, commands_);
          onChanged();
        } else {
          commandsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.srl.action.Command commands = 1;</code>
       */
      public Builder clearCommands() {
        if (commandsBuilder_ == null) {
          commands_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          commandsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.srl.action.Command commands = 1;</code>
       */
      public Builder removeCommands(int index) {
        if (commandsBuilder_ == null) {
          ensureCommandsIsMutable();
          commands_.remove(index);
          onChanged();
        } else {
          commandsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.srl.action.Command commands = 1;</code>
       */
      public protobuf.srl.action.Action.Command.Builder getCommandsBuilder(
          int index) {
        return getCommandsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protobuf.srl.action.Command commands = 1;</code>
       */
      public protobuf.srl.action.Action.CommandOrBuilder getCommandsOrBuilder(
          int index) {
        if (commandsBuilder_ == null) {
          return commands_.get(index);  } else {
          return commandsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protobuf.srl.action.Command commands = 1;</code>
       */
      public java.util.List<? extends protobuf.srl.action.Action.CommandOrBuilder> 
           getCommandsOrBuilderList() {
        if (commandsBuilder_ != null) {
          return commandsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(commands_);
        }
      }
      /**
       * <code>repeated .protobuf.srl.action.Command commands = 1;</code>
       */
      public protobuf.srl.action.Action.Command.Builder addCommandsBuilder() {
        return getCommandsFieldBuilder().addBuilder(
            protobuf.srl.action.Action.Command.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.srl.action.Command commands = 1;</code>
       */
      public protobuf.srl.action.Action.Command.Builder addCommandsBuilder(
          int index) {
        return getCommandsFieldBuilder().addBuilder(
            index, protobuf.srl.action.Action.Command.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.srl.action.Command commands = 1;</code>
       */
      public java.util.List<protobuf.srl.action.Action.Command.Builder> 
           getCommandsBuilderList() {
        return getCommandsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          protobuf.srl.action.Action.Command, protobuf.srl.action.Action.Command.Builder, protobuf.srl.action.Action.CommandOrBuilder> 
          getCommandsFieldBuilder() {
        if (commandsBuilder_ == null) {
          commandsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              protobuf.srl.action.Action.Command, protobuf.srl.action.Action.Command.Builder, protobuf.srl.action.Action.CommandOrBuilder>(
                  commands_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          commands_ = null;
        }
        return commandsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.srl.action.Update)
    }

    static {
      defaultInstance = new Update(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.srl.action.Update)
  }

  public interface CommandOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .protobuf.srl.action.CommandType commandType = 1;
    /**
     * <code>required .protobuf.srl.action.CommandType commandType = 1;</code>
     */
    boolean hasCommandType();
    /**
     * <code>required .protobuf.srl.action.CommandType commandType = 1;</code>
     */
    protobuf.srl.action.Action.CommandType getCommandType();

    // required bool isUserCreated = 2;
    /**
     * <code>required bool isUserCreated = 2;</code>
     */
    boolean hasIsUserCreated();
    /**
     * <code>required bool isUserCreated = 2;</code>
     */
    boolean getIsUserCreated();

    // required bytes commandData = 3;
    /**
     * <code>required bytes commandData = 3;</code>
     */
    boolean hasCommandData();
    /**
     * <code>required bytes commandData = 3;</code>
     */
    com.google.protobuf.ByteString getCommandData();

    // optional int64 time = 4;
    /**
     * <code>optional int64 time = 4;</code>
     */
    boolean hasTime();
    /**
     * <code>optional int64 time = 4;</code>
     */
    long getTime();

    // optional string commandId = 5;
    /**
     * <code>optional string commandId = 5;</code>
     */
    boolean hasCommandId();
    /**
     * <code>optional string commandId = 5;</code>
     */
    java.lang.String getCommandId();
    /**
     * <code>optional string commandId = 5;</code>
     */
    com.google.protobuf.ByteString
        getCommandIdBytes();
  }
  /**
   * Protobuf type {@code protobuf.srl.action.Command}
   *
   * <pre>
   * inheritance does not exist so this will replace shape
   * </pre>
   */
  public static final class Command extends
      com.google.protobuf.GeneratedMessage
      implements CommandOrBuilder {
    // Use Command.newBuilder() to construct.
    private Command(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Command(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Command defaultInstance;
    public static Command getDefaultInstance() {
      return defaultInstance;
    }

    public Command getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Command(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              protobuf.srl.action.Action.CommandType value = protobuf.srl.action.Action.CommandType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                commandType_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              isUserCreated_ = input.readBool();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              commandData_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              time_ = input.readInt64();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              commandId_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.srl.action.Action.internal_static_protobuf_srl_action_Command_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.srl.action.Action.internal_static_protobuf_srl_action_Command_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.srl.action.Action.Command.class, protobuf.srl.action.Action.Command.Builder.class);
    }

    public static com.google.protobuf.Parser<Command> PARSER =
        new com.google.protobuf.AbstractParser<Command>() {
      public Command parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Command(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Command> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .protobuf.srl.action.CommandType commandType = 1;
    public static final int COMMANDTYPE_FIELD_NUMBER = 1;
    private protobuf.srl.action.Action.CommandType commandType_;
    /**
     * <code>required .protobuf.srl.action.CommandType commandType = 1;</code>
     */
    public boolean hasCommandType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .protobuf.srl.action.CommandType commandType = 1;</code>
     */
    public protobuf.srl.action.Action.CommandType getCommandType() {
      return commandType_;
    }

    // required bool isUserCreated = 2;
    public static final int ISUSERCREATED_FIELD_NUMBER = 2;
    private boolean isUserCreated_;
    /**
     * <code>required bool isUserCreated = 2;</code>
     */
    public boolean hasIsUserCreated() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bool isUserCreated = 2;</code>
     */
    public boolean getIsUserCreated() {
      return isUserCreated_;
    }

    // required bytes commandData = 3;
    public static final int COMMANDDATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString commandData_;
    /**
     * <code>required bytes commandData = 3;</code>
     */
    public boolean hasCommandData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes commandData = 3;</code>
     */
    public com.google.protobuf.ByteString getCommandData() {
      return commandData_;
    }

    // optional int64 time = 4;
    public static final int TIME_FIELD_NUMBER = 4;
    private long time_;
    /**
     * <code>optional int64 time = 4;</code>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 time = 4;</code>
     */
    public long getTime() {
      return time_;
    }

    // optional string commandId = 5;
    public static final int COMMANDID_FIELD_NUMBER = 5;
    private java.lang.Object commandId_;
    /**
     * <code>optional string commandId = 5;</code>
     */
    public boolean hasCommandId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string commandId = 5;</code>
     */
    public java.lang.String getCommandId() {
      java.lang.Object ref = commandId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          commandId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string commandId = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCommandIdBytes() {
      java.lang.Object ref = commandId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        commandId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      commandType_ = protobuf.srl.action.Action.CommandType.ADD_STROKE;
      isUserCreated_ = false;
      commandData_ = com.google.protobuf.ByteString.EMPTY;
      time_ = 0L;
      commandId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCommandType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsUserCreated()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCommandData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, commandType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, isUserCreated_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, commandData_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, time_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getCommandIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, commandType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isUserCreated_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, commandData_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, time_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getCommandIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.srl.action.Action.Command parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.srl.action.Action.Command parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.srl.action.Action.Command parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.srl.action.Action.Command parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.srl.action.Action.Command parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.srl.action.Action.Command parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.srl.action.Action.Command parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.srl.action.Action.Command parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.srl.action.Action.Command parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.srl.action.Action.Command parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.srl.action.Action.Command prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.srl.action.Command}
     *
     * <pre>
     * inheritance does not exist so this will replace shape
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.srl.action.Action.CommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.srl.action.Action.internal_static_protobuf_srl_action_Command_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.srl.action.Action.internal_static_protobuf_srl_action_Command_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.srl.action.Action.Command.class, protobuf.srl.action.Action.Command.Builder.class);
      }

      // Construct using protobuf.srl.action.Action.Command.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        commandType_ = protobuf.srl.action.Action.CommandType.ADD_STROKE;
        bitField0_ = (bitField0_ & ~0x00000001);
        isUserCreated_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        commandData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        time_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        commandId_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.srl.action.Action.internal_static_protobuf_srl_action_Command_descriptor;
      }

      public protobuf.srl.action.Action.Command getDefaultInstanceForType() {
        return protobuf.srl.action.Action.Command.getDefaultInstance();
      }

      public protobuf.srl.action.Action.Command build() {
        protobuf.srl.action.Action.Command result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.srl.action.Action.Command buildPartial() {
        protobuf.srl.action.Action.Command result = new protobuf.srl.action.Action.Command(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.commandType_ = commandType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.isUserCreated_ = isUserCreated_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.commandData_ = commandData_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.commandId_ = commandId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.srl.action.Action.Command) {
          return mergeFrom((protobuf.srl.action.Action.Command)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.srl.action.Action.Command other) {
        if (other == protobuf.srl.action.Action.Command.getDefaultInstance()) return this;
        if (other.hasCommandType()) {
          setCommandType(other.getCommandType());
        }
        if (other.hasIsUserCreated()) {
          setIsUserCreated(other.getIsUserCreated());
        }
        if (other.hasCommandData()) {
          setCommandData(other.getCommandData());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasCommandId()) {
          bitField0_ |= 0x00000010;
          commandId_ = other.commandId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCommandType()) {
          
          return false;
        }
        if (!hasIsUserCreated()) {
          
          return false;
        }
        if (!hasCommandData()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.srl.action.Action.Command parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.srl.action.Action.Command) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .protobuf.srl.action.CommandType commandType = 1;
      private protobuf.srl.action.Action.CommandType commandType_ = protobuf.srl.action.Action.CommandType.ADD_STROKE;
      /**
       * <code>required .protobuf.srl.action.CommandType commandType = 1;</code>
       */
      public boolean hasCommandType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .protobuf.srl.action.CommandType commandType = 1;</code>
       */
      public protobuf.srl.action.Action.CommandType getCommandType() {
        return commandType_;
      }
      /**
       * <code>required .protobuf.srl.action.CommandType commandType = 1;</code>
       */
      public Builder setCommandType(protobuf.srl.action.Action.CommandType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        commandType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .protobuf.srl.action.CommandType commandType = 1;</code>
       */
      public Builder clearCommandType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        commandType_ = protobuf.srl.action.Action.CommandType.ADD_STROKE;
        onChanged();
        return this;
      }

      // required bool isUserCreated = 2;
      private boolean isUserCreated_ ;
      /**
       * <code>required bool isUserCreated = 2;</code>
       */
      public boolean hasIsUserCreated() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bool isUserCreated = 2;</code>
       */
      public boolean getIsUserCreated() {
        return isUserCreated_;
      }
      /**
       * <code>required bool isUserCreated = 2;</code>
       */
      public Builder setIsUserCreated(boolean value) {
        bitField0_ |= 0x00000002;
        isUserCreated_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool isUserCreated = 2;</code>
       */
      public Builder clearIsUserCreated() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isUserCreated_ = false;
        onChanged();
        return this;
      }

      // required bytes commandData = 3;
      private com.google.protobuf.ByteString commandData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes commandData = 3;</code>
       */
      public boolean hasCommandData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes commandData = 3;</code>
       */
      public com.google.protobuf.ByteString getCommandData() {
        return commandData_;
      }
      /**
       * <code>required bytes commandData = 3;</code>
       */
      public Builder setCommandData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        commandData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes commandData = 3;</code>
       */
      public Builder clearCommandData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        commandData_ = getDefaultInstance().getCommandData();
        onChanged();
        return this;
      }

      // optional int64 time = 4;
      private long time_ ;
      /**
       * <code>optional int64 time = 4;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 time = 4;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>optional int64 time = 4;</code>
       */
      public Builder setTime(long value) {
        bitField0_ |= 0x00000008;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 time = 4;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        time_ = 0L;
        onChanged();
        return this;
      }

      // optional string commandId = 5;
      private java.lang.Object commandId_ = "";
      /**
       * <code>optional string commandId = 5;</code>
       */
      public boolean hasCommandId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string commandId = 5;</code>
       */
      public java.lang.String getCommandId() {
        java.lang.Object ref = commandId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          commandId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string commandId = 5;</code>
       */
      public com.google.protobuf.ByteString
          getCommandIdBytes() {
        java.lang.Object ref = commandId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          commandId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string commandId = 5;</code>
       */
      public Builder setCommandId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        commandId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string commandId = 5;</code>
       */
      public Builder clearCommandId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        commandId_ = getDefaultInstance().getCommandId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string commandId = 5;</code>
       */
      public Builder setCommandIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        commandId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.srl.action.Command)
    }

    static {
      defaultInstance = new Command(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.srl.action.Command)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_srl_action_Update_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_srl_action_Update_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_srl_action_Command_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_srl_action_Command_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022input/action.proto\022\023protobuf.srl.actio" +
      "n\"8\n\006Update\022.\n\010commands\030\001 \003(\0132\034.protobuf" +
      ".srl.action.Command\"\215\001\n\007Command\0225\n\013comma" +
      "ndType\030\001 \002(\0162 .protobuf.srl.action.Comma" +
      "ndType\022\025\n\risUserCreated\030\002 \002(\010\022\023\n\013command" +
      "Data\030\003 \002(\014\022\014\n\004time\030\004 \001(\003\022\021\n\tcommandId\030\005 " +
      "\001(\t*[\n\013CommandType\022\016\n\nADD_STROKE\020\000\022\r\n\tAD" +
      "D_SHAPE\020\001\022\023\n\017REPACKAGE_SHAPE\020\002\022\030\n\024FORCE_" +
      "INTERPRETATION\020\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protobuf_srl_action_Update_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protobuf_srl_action_Update_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_srl_action_Update_descriptor,
              new java.lang.String[] { "Commands", });
          internal_static_protobuf_srl_action_Command_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protobuf_srl_action_Command_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_srl_action_Command_descriptor,
              new java.lang.String[] { "CommandType", "IsUserCreated", "CommandData", "Time", "CommandId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
