# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: input/commands.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='input/commands.proto',
  package='protobuf.srl.action.commands',
  serialized_pb='\n\x14input/commands.proto\x12\x1cprotobuf.srl.action.commands\"C\n\x0cPackageShape\x12\x16\n\x0enewContainerId\x18\x01 \x02(\t\x12\x1b\n\x13shapesToBeContained\x18\x02 \x03(\t\"\x1b\n\tAddStroke\x12\x0e\n\x06stroke\x18\x01 \x02(\x0c\"&\n\x0bRemoveShape\x12\x17\n\x0fshapeToRemoveId\x18\x01 \x02(\t\"\x19\n\x08\x41\x64\x64Shape\x12\r\n\x05shape\x18\x01 \x02(\x0c\">\n\x13\x46orceInterpretation\x12\x16\n\x0einterpretation\x18\x01 \x02(\x0c\x12\x0f\n\x07shapeId\x18\x02 \x02(\t')




_PACKAGESHAPE = _descriptor.Descriptor(
  name='PackageShape',
  full_name='protobuf.srl.action.commands.PackageShape',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='newContainerId', full_name='protobuf.srl.action.commands.PackageShape.newContainerId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shapesToBeContained', full_name='protobuf.srl.action.commands.PackageShape.shapesToBeContained', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=54,
  serialized_end=121,
)


_ADDSTROKE = _descriptor.Descriptor(
  name='AddStroke',
  full_name='protobuf.srl.action.commands.AddStroke',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stroke', full_name='protobuf.srl.action.commands.AddStroke.stroke', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=123,
  serialized_end=150,
)


_REMOVESHAPE = _descriptor.Descriptor(
  name='RemoveShape',
  full_name='protobuf.srl.action.commands.RemoveShape',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shapeToRemoveId', full_name='protobuf.srl.action.commands.RemoveShape.shapeToRemoveId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=152,
  serialized_end=190,
)


_ADDSHAPE = _descriptor.Descriptor(
  name='AddShape',
  full_name='protobuf.srl.action.commands.AddShape',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shape', full_name='protobuf.srl.action.commands.AddShape.shape', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=192,
  serialized_end=217,
)


_FORCEINTERPRETATION = _descriptor.Descriptor(
  name='ForceInterpretation',
  full_name='protobuf.srl.action.commands.ForceInterpretation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='interpretation', full_name='protobuf.srl.action.commands.ForceInterpretation.interpretation', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shapeId', full_name='protobuf.srl.action.commands.ForceInterpretation.shapeId', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=219,
  serialized_end=281,
)

DESCRIPTOR.message_types_by_name['PackageShape'] = _PACKAGESHAPE
DESCRIPTOR.message_types_by_name['AddStroke'] = _ADDSTROKE
DESCRIPTOR.message_types_by_name['RemoveShape'] = _REMOVESHAPE
DESCRIPTOR.message_types_by_name['AddShape'] = _ADDSHAPE
DESCRIPTOR.message_types_by_name['ForceInterpretation'] = _FORCEINTERPRETATION

class PackageShape(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PACKAGESHAPE

  # @@protoc_insertion_point(class_scope:protobuf.srl.action.commands.PackageShape)

class AddStroke(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ADDSTROKE

  # @@protoc_insertion_point(class_scope:protobuf.srl.action.commands.AddStroke)

class RemoveShape(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REMOVESHAPE

  # @@protoc_insertion_point(class_scope:protobuf.srl.action.commands.RemoveShape)

class AddShape(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ADDSHAPE

  # @@protoc_insertion_point(class_scope:protobuf.srl.action.commands.AddShape)

class ForceInterpretation(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FORCEINTERPRETATION

  # @@protoc_insertion_point(class_scope:protobuf.srl.action.commands.ForceInterpretation)


# @@protoc_insertion_point(module_scope)
